name:                calculator
version:             0.1.0.0
license:             BSD3
author:              "Mattox Beckman"
maintainer:          "mattox@illinois.edu"
copyright:           "2020 Mattox Beckman"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - unordered-containers

tests:
  tests-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calculator 
    - unordered-containers
    - QuickCheck
    - HUnit
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
